services:
  - type: web
    name: milele-chat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: milele-db
          property: connectionString
    plan: free
    disk:
      name: milele-data
      mountPath: /opt/render/project/src/static/uploads
      sizeGB: 1

databases:
  - name: milele-db
    databaseName: milele
    user: milele
    plan: free 